#!/bin/bash

#script directory
module load freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
module load ants
# study name and directory
export STUDY=wr
export SRCDIR=$HOME/analysis/wr
export STUDYDIR=$STOCKYARD2/ls6/wr
export BATCHDIR=$STOCKYARD2/ls6/wr/batch/launchscripts
export FSDIR=$SCRATCH/wr/prepro/derivatives/fmriprep/sourcedata/freesurfer
export FMDIR=$SCRATCH/wr/prepro/derivatives/fmriprep/
export CORR=/corral-repl/utexas/prestonlab/prisma_testing
# add analysis scripts to path
export PATH=$PATH:$SRCDIR/bin
export STUDYDIR=$STOCKYARD2/ls6/wr
. $STOCKYARD2/ls6/tempenv/bin/activate
export PATH=$PATH:$SRCDIR/bin
# subjects
export SUBJNOS=200:201
export SUBIDS=wr_200:wr_201
export BIDIDS=wr200:wr201
